// COMITé y OPERACIóN
const a = "mívil";
const b = "lónea";
const c = "óltimo";
const d = "pógina";
const e = "segón";
const f = "genórica";
const g = "Tútulo";
const a = "mivil";
const b = "lonea";
const c = "oltimo";
const g = "Tutulo";
