$root='api/LuxuryApp.Application/Modules/MantenimientoLuxuryApp/Medidores'; $dto="$root/DTOs"
$specs=@(
 @{Old='MedidorAddOrEditDTO'; Base='Meter'; ReadOld='MedidorDTO'; Read='MeterDTO'},
 @{Old='MedidorCategoriaAddOrEditDTO'; Base='MeterCategory'; ReadOld='MedidorCategoriaDTO'; Read='MeterCategoryDTO'},
 @{Old='MedidorLecturaAddOrEditDTO'; Base='MeterReading'; ReadOld='MedidorLecturaDTO'; Read='MeterReadingDTO'}
)
foreach($s in $specs){$src=Get-Content "$dto/$($s.Old).cs" -Raw; foreach($kind in @('Create','Update')){$n="$kind$($s.Base)DTO"; Set-Content "$dto/$n.cs" ($src.Replace($s.Old,$n)) -NoNewline}; $read=Get-Content "$dto/$($s.ReadOld).cs" -Raw; Set-Content "$dto/$($s.Read).cs" ($read.Replace($s.ReadOld,$s.Read)) -NoNewline; Remove-Item "$dto/$($s.Old).cs","$dto/$($s.ReadOld).cs"}
$map=@{'MedidorAddOrEditDTO'='CreateMeterDTO';'MedidorDTO'='MeterDTO';'MedidorCategoriaAddOrEditDTO'='CreateMeterCategoryDTO';'MedidorCategoriaDTO'='MeterCategoryDTO';'MedidorLecturaAddOrEditDTO'='CreateMeterReadingDTO';'MedidorLecturaDTO'='MeterReadingDTO';'MedidorLecturaCharDTO'='MeterReadingChartDTO';'MedidorLecturaCharMonthDTO'='MonthlyMeterReadingChartDTO';'MedidorLecturaExcelDTO'='MeterReadingExcelDTO'}
Get-ChildItem $root -Recurse -File -Filter *.cs | ForEach-Object{$c=Get-Content $_.FullName -Raw; foreach($k in $map.Keys){$c=$c.Replace($k,$map[$k])}; Set-Content $_.FullName $c -NoNewline}
Get-ChildItem $root -Recurse -File -Filter *.cs | ForEach-Object{$c=Get-Content $_.FullName -Raw; $c=$c.Replace('UpdateAsync(Guid id, CreateMeterDTO','UpdateAsync(Guid id, UpdateMeterDTO').Replace('UpdateAsync(Guid id, CreateMeterCategoryDTO','UpdateAsync(Guid id, UpdateMeterCategoryDTO').Replace('UpdateAsync(Guid id, CreateMeterReadingDTO','UpdateAsync(Guid id, UpdateMeterReadingDTO').Replace('MapPut("{id:guid}", async (Guid id, CreateMeterDTO','MapPut("{id:guid}", async (Guid id, UpdateMeterDTO').Replace('MapPut("{id:guid}", async (Guid id, CreateMeterCategoryDTO','MapPut("{id:guid}", async (Guid id, UpdateMeterCategoryDTO').Replace('MapPut("{id:guid}", async (Guid id, CreateMeterReadingDTO','MapPut("{id:guid}", async (Guid id, UpdateMeterReadingDTO'); Set-Content $_.FullName $c -NoNewline}
